Development
starlinskii/Typing-Trainer pull request #2
Opened 2024-04-09 08:39 UTC by starlinskii

Request review

Project is still to end
(need to write tests and add interesting texts for typing)

2024-04-11 00:16 UTC, KatyaProkhorchuk requested changes
надо поправить и ответить на вопрос

2024-04-11 00:16 UTC, KatyaProkhorchuk commented on Interfaces.py
> +from tkinter import *
писала в группу что так делать не нужно, как думаешь почему?

2024-04-11 00:16 UTC, KatyaProkhorchuk commented on requirements.txt
> +pip install tkinter
requirements нужно сгенерировать
https://ru.stackoverflow.com/questions/396133/requirements-txt-%D0%BA%D0%B0%D0%BA-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C

2024-04-11 08:57 UTC, starlinskii commented on Interfaces.py
> +from tkinter import *
Видимо проблема как в плюсах писать using namespace std. Подключается много мусора из всей библиотеки, какие то функции/объекты могут перекрывать друг друга

2024-04-25 09:46 UTC, KatyaProkhorchuk requested changes

2024-04-25 09:46 UTC, KatyaProkhorchuk commented on requirements.txt
> +appdirs==1.4.4
ты вроде бы ничего не используешь кроме tkinter
получается что для запуска твоей программы я установлю кучу ненужного...
что бы не было такой каши нужно работать в виртуальным окружении

2024-04-28 17:53 UTC, starlinskii commented on requirements.txt
> +appdirs==1.4.4
Сгенерил requirements, использую виртуальную среду - он пустой оказался) Погуглил - ткинтер и вправду встроен оказывается

2024-05-07 08:24 UTC, KatyaProkhorchuk approved these changes
ok

2025-05-26 14:35 UTC, merged